In [1]:
import numpy as np
from scipy import linalg

In [2]:
# Bài 1
ma_tran_A = np.array([[1, 0, 0, 0, 2],
                    [0, 0, 3, 0, 0],
                    [0, 0, 0, 0, 0],
                    [0, 2, 0, 0, 0]])

ma_tran_A = np.array([[3, 2, 2],
                      [2, 3, -2]])

def tinh_svd(ma_tran_A):
    from scipy import linalg
    ma_tran_U, ma_tran_Sigma, ma_tran_VT = linalg.svd(ma_tran_A)
    m = ma_tran_A.shape[0]
    n = ma_tran_A.shape[1]
    sigma_matrix = np.zeros((m, n))
    np.fill_diagonal(sigma_matrix, ma_tran_Sigma)
    return ma_tran_U, sigma_matrix, ma_tran_VT

In [3]:
U, s, Vt = tinh_svd(ma_tran_A)
print(U@s@Vt)

[[ 3.  2.  2.]
 [ 2.  3. -2.]]


In [4]:
# Bài 2
ma_tran_A = np.array([[1, 0, 0, 0, 2],
            [0, 0, 3, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 2, 0, 0, 0]])

def tinh_compact_svd(ma_tran_A):
    from scipy import linalg
    ma_tran_U, Sigma, ma_tran_VT = linalg.svd(ma_tran_A)
    r = np.count_nonzero(np.diag(Sigma))
    ma_tran_SigmaR = np.zeros((r, r))
    np.fill_diagonal(ma_tran_SigmaR, Sigma)
    ma_tran_Ur = ma_tran_U[:, :r]
    ma_tran_VTr = ma_tran_VT[:r, :]
    return ma_tran_Ur, ma_tran_SigmaR, ma_tran_VTr

In [5]:
U, s, Vt = tinh_compact_svd(ma_tran_A)
print(U@s@Vt)

[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [6]:
# Bài 3
A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
            [0.2, 1.01, 0.3, 0.8, 0.4],
            [1, 1.002, 2, 0.98, 2],
            [0.3, 2, 0.4, 1.01, 0.9],
            [1.1, 0.2, 0.03, 2, 0.87]])

def tinh_luong_thong_tin(ma_tran_A, so_ky_di_giu):
    from scipy import linalg
    ma_tran_U, Sigma, ma_tran_VT = linalg.svd(ma_tran_A)
    ma_tran_Sk = np.diag(Sigma[:so_ky_di_giu])
    r = np.count_nonzero(np.diag(Sigma))
    ma_tran_Uk = ma_tran_U[:, :so_ky_di_giu]
    ma_tran_VTk = ma_tran_VT[:so_ky_di_giu, :]
    sum = np.sum(Sigma[:so_ky_di_giu]**2) / np.sum(Sigma[:r]**2)
    phan_tram_thong_tin_luu_giu = sum * 100
    return phan_tram_thong_tin_luu_giu, ma_tran_Uk, ma_tran_Sk, ma_tran_VTk

In [7]:
I, U, s, Vt = tinh_luong_thong_tin(A, 4)
print(U)
print(s)
print(Vt)
print(U@s@Vt)
print(I)

[[-0.32813554  0.32928789  0.08780746 -0.88098834]
 [-0.27374756  0.09123211  0.31504405  0.16061502]
 [-0.64816455 -0.65873014 -0.3795124  -0.04270121]
 [-0.46609071  0.0207275   0.71918456  0.25646457]
 [-0.4243012   0.66999341 -0.4814364   0.36119923]]
[[4.68190663 0.         0.         0.        ]
 [0.         1.79325215 0.         0.        ]
 [0.         0.         1.57960998 0.        ]
 [0.         0.         0.         0.54903356]]
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [-0.3428965   0.86035897 -0.23658964 -0.1699711  -0.2394569 ]
 [-0.77612359 -0.16080247 -0.18212689  0.3391472   0.47284639]]
[[1.00962046 0.89993951 0.20070897 1.00151623 0.29925926]
 [0.24982131 1.01794002 0.20693675 0.73223718 0.49723352]
 [1.00057175 1.00209112 1.998932   0.97922235 2.00111586]
 [0.27500095 1.9960159  0.44669673 1.04400163 0.85121073]
 [1.09473797 0.19916139 0.03982916 2.00715698 0.85973038]]
99.88593923

In [8]:
# Bài 4
ma_tran_A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3],
            [0.2, 1.01, 0.3, 0.8, 0.4],
            [1, 1.002, 2, 0.98, 2],
            [0.3, 2, 0.4, 1.01, 0.9],
            [1.1, 0.2, 0.03, 2, 0.87]])

def tinh_luong_ky_di_can(ma_tran_A, phan_tram_thong_tin_luu_giu):
    from scipy import linalg
    ma_tran_U, Sigma, ma_tran_VT = linalg.svd(ma_tran_A)
    r = np.count_nonzero(np.diag(Sigma))
    so_ky_di_can = 1
    while (True):
        sum = np.sum(Sigma[:so_ky_di_can]**2) / np.sum(Sigma[:r]**2)
        if sum * 100 >= phan_tram_thong_tin_luu_giu:
            break
        so_ky_di_can+=1
    ma_tran_Uk = ma_tran_U[:, :so_ky_di_can]
    ma_tran_VTk = ma_tran_VT[:so_ky_di_can, :]
    ma_tran_Sk = np.diag(Sigma[:so_ky_di_can])
    return so_ky_di_can, ma_tran_Uk, ma_tran_Sk, ma_tran_VTk

In [9]:
k, U, s, VT = tinh_luong_ky_di_can(ma_tran_A, 90)
print(U)
print(s)
print(VT)
print(U@s@VT)
print(k)

[[-0.32813554  0.32928789  0.08780746]
 [-0.27374756  0.09123211  0.31504405]
 [-0.64816455 -0.65873014 -0.3795124 ]
 [-0.46609071  0.0207275   0.71918456]
 [-0.4243012   0.66999341 -0.4814364 ]]
[[4.68190663 0.         0.        ]
 [0.         1.79325215 0.        ]
 [0.         0.         1.57960998]]
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [-0.3428965   0.86035897 -0.23658964 -0.1699711  -0.2394569 ]]
[[0.63421555 0.82216062 0.11261562 1.16555907 0.52797136]
 [0.31826225 1.03212007 0.22299725 0.70233015 0.45553649]
 [0.982376   0.9983212  1.99466215 0.98717345 2.01220145]
 [0.3842851  2.01865812 0.47234159 0.99624711 0.78463034]
 [1.24865143 0.23105021 0.07594684 1.93990053 0.76595998]]
3
